name: moss integration test
on:
  pull_request
jobs:
  tests:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up node16.16.0
        uses: actions/setup-node@v3
        with:
          node-version: '16.16.0'
      - name: Set up python3.8
        uses: actions/setup-python@v3
        with:
          python-version: 3.8
      - name: Run install script
        run: |
          python3 ubuntu_22_install.py -action
      - name: Nosetests
        run: |
          nosetests

