name: LPF integration test
on:
  pull_request
jobs:
  tests:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up node16.16.0
        uses: actions/setup-node@v3
        with:
          node-version: '16.16.0'
      - name: Set up python3.8
        uses: actions/setup-python@v3
        with:
          python-version: 3.8
      - name: Install Requirements
        run: |
          pip install -r requirements.txt
      - name: Run install script
        run: |
          ./LocalPathogenFinder install -ci
      - name: LPF init
        run: |
          python3 /opt/LPF/quick_test.py
      - name: Nosetests
        run: |
           nose2 -s tests/integration --verbosity 2

