name: moss integration test
on:
  pull_request
jobs:
  tests:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up node14
        uses: actions/setup-node@v3
        with:
          node-version: '14'
      - name: Set up python3.8
        uses: actions/setup-python@v3
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python3 docker_images.py
      - name: Install KMA and CCphylo
        run: |
          sudo apt-get install libz-dev
          git clone https://bitbucket.org/genomicepidemiology/kma.git; cd kma; make; cd ..;
          git clone https://bitbucket.org/genomicepidemiology/ccphylo.git; cd ccphylo && make; cd ..;
      - name: Run Pylint
        run: |
          find . -type f -name "*.py" | xargs pylint --fail-under 1
      - name: Nosetests
        run: |
          nosetests
      - name: Run install script
        run: |
          python3 ubuntu_22_install.py
          cd /opt/moss
